# Generated by Django 6.0 on 2025-12-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('job_type', models.CharField(choices=[('part_time', 'part_time'), ('full_time', 'full_time')], default='part_time', max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('responsibility', models.TextField(blank=True, default='none', max_length=200, null=True)),
                ('qualifications', models.TextField(blank=True, default='none', max_length=200, null=True)),
                ('vacancy', models.IntegerField()),
                ('salary', models.CharField(max_length=10)),
                ('benefits', models.TextField(blank=True, default='none', max_length=200, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
